# WHY TO USE NUMPY ??

<h2>Numpy is fast</h2> 
See <b>Python is an interpreted Programming Language</b>(Which means each line is executed one by one) which makes it <b>SLOWER</b>
as compared to <b> C / C++ </b> as these Programs are Compiler based which means these are complied first and executed Which is better for computers to understand.


🟠Lists in Pythons are basically arrays in C which are linked using Pointer which makes it slower and time consuming for Big Millions and Trillions of data.

🔵Here Numpy comes into Play as most of its  its coding is done in C language which makes it faster for handling big data and it takes less time.

In [10]:
import numpy as np

In [11]:
arr = np.arange(100000)

In [12]:
pylist = list(range(100000))

In [13]:
%time for _i in range (10): [item*3 for item in pylist]

CPU times: total: 15.6 ms
Wall time: 34 ms


In [14]:
%time for _i in range (10): arr = arr*3

CPU times: total: 0 ns
Wall time: 995 µs


# NUMPY ARRAY

In [15]:
np.array([2,3,9,69,96])

array([ 2,  3,  9, 69, 96])

### Functions In Numpy Array

In [16]:
import numpy as np
array1 = np.array([[2,3,4,50,69],[69,90,100,20,4]], dtype = "int32")
print(array1)

[[  2   3   4  50  69]
 [ 69  90 100  20   4]]
