# Axis, Sorting & Other useful functions in Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4,5,6]])

In [3]:
a.sum(axis = 0) # axis=0 For Column

array([5, 7, 9])

In [4]:
a.sum(axis = 1) # axis = 1 for Rows

array([ 6, 15])

In [5]:
b = np.array([[77,8,90],[21,18,64]])

In [6]:
a.dot(b.transpose())

array([[363, 249],
       [888, 558]])

In [7]:
len(dir(np))

591

In [8]:
np.cross(a,b)

array([[ 156,  141, -146],
       [ 212, -130,  -33]])

In [10]:
np.sort(b)

array([[ 8, 77, 90],
       [18, 21, 64]])

# Numpy Argsort,Argmin, Argmax function

In [11]:
import numpy as np

In [12]:
c = np.arange(18)

In [13]:
c = c.reshape(6,3)

In [14]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
np.argsort(c, axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]], dtype=int64)

In [16]:
np.argmin(c)

0

In [17]:
np.argmax(c)

17